variable "DOCDB_ENGINE" {}
variable "DOCDB_ENGINE_VERSION" {}
variable "DOCDB_NODE_TYPE" {}
variable "DOCDB_NODE_COUNT" {}
variable "DOCDB_FAMILY" {}
variable "DOCDB_SKIP_FINAL_SNAPSHOT" {}
variable "FAMILY" {}
variable "ENV" {}
variable "COMPONENT" {}
variable "VPC_ID" {}
variable "VPC_CIDR" {}
variable "SUBNET_IDS" {}